CREATE TABLE IF NOT EXISTS matiere_id (
  name TEXT PRIMARY KEY
);

INSERT INTO matiere_id (name) VALUES ('Anatomie et Cytologie Pathologiques');
INSERT INTO matiere_id (name) VALUES ('Anesthésie - Réanimation');
INSERT INTO matiere_id (name) VALUES ('Cancérologie');
INSERT INTO matiere_id (name) VALUES ('Chirurgie Digestive');
INSERT INTO matiere_id (name) VALUES ('CMF');
INSERT INTO matiere_id (name) VALUES ('Dermatologie');
INSERT INTO matiere_id (name) VALUES ('Douleurs - Soins Palliatifs');
INSERT INTO matiere_id (name) VALUES ('Endocrinologie');
INSERT INTO matiere_id (name) VALUES ('Génétique');
INSERT INTO matiere_id (name) VALUES ('Gériatrie');
INSERT INTO matiere_id (name) VALUES ('Gynécologie Médicale');
INSERT INTO matiere_id (name) VALUES ('Gynécologie - Obstétrique');
INSERT INTO matiere_id (name) VALUES ('Hématologie');
INSERT INTO matiere_id (name) VALUES ('HGE');
INSERT INTO matiere_id (name) VALUES ('Imagerie Médicale');
INSERT INTO matiere_id (name) VALUES ('Immunopathologie');
INSERT INTO matiere_id (name) VALUES ('Infectiologie');
INSERT INTO matiere_id (name) VALUES ('Médecine Cardiovasculaire');
INSERT INTO matiere_id (name) VALUES ('Médecine Générale');
INSERT INTO matiere_id (name) VALUES ('MIR - Urgences');
INSERT INTO matiere_id (name) VALUES ('Médecine Interne');
INSERT INTO matiere_id (name) VALUES ('Médecine Légale - Médecine du Travail');
INSERT INTO matiere_id (name) VALUES ('Médecine Moléculaire');
INSERT INTO matiere_id (name) VALUES ('MPR');
INSERT INTO matiere_id (name) VALUES ('Médecine Vasculaire');
INSERT INTO matiere_id (name) VALUES ('Néphrologie');
INSERT INTO matiere_id (name) VALUES ('Neurochirurgie');
INSERT INTO matiere_id (name) VALUES ('Neurologie');
INSERT INTO matiere_id (name) VALUES ('Nutrition');
INSERT INTO matiere_id (name) VALUES ('Ophtalmologie');
INSERT INTO matiere_id (name) VALUES ('ORL');
INSERT INTO matiere_id (name) VALUES ('Orthopédie - Traumatologie');
INSERT INTO matiere_id (name) VALUES ('Parasitologie');
INSERT INTO matiere_id (name) VALUES ('Pédiatrie');
INSERT INTO matiere_id (name) VALUES ('Pneumologie');
INSERT INTO matiere_id (name) VALUES ('Psychiatrie - Addictologie');
INSERT INTO matiere_id (name) VALUES ('Rhumatologie');
INSERT INTO matiere_id (name) VALUES ('Santé Publique');
INSERT INTO matiere_id (name) VALUES ('Thérapeutique');
INSERT INTO matiere_id (name) VALUES ('Urologie');