CREATE TABLE IF NOT EXISTS nouveau_programme_r2c (
  unnamed_0 TEXT,
  unnamed_1 TEXT
);

INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('1', 'La relation médecin-malade dans le cadre du colloque singulier ou au sein d''une équipe, le cas échéant pluriprofessionnelle. La communication avec le patient et son entourage. L''annonce d''une maladie grave ou létale ou d''un dommage associé aux soins. La formation du patient. La personnalisation de la prise en charge médicale.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('2', 'Les valeurs professionnelles du médecin et des autres professions de santé');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('3', 'Le raisonnement et la décision en médecine. La médecine fondée sur les preuves (Evidence Based Medicine, EBM). La décision médicale partagée. La controverse.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('4', 'Qualité et sécurité des soins. La sécurité du patient. La gestion des risques. Les événements indésirables associés aux soins (EIAS). Démarche qualité et évaluation des pratiques professionnelles');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('5', 'La gestion des erreurs et des plaintes ; l''aléa thérapeutique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('6', 'L''organisation de l''exercice clinique et les méthodes qui permettent de sécuriser le parcours du patient');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('7', 'Les droits individuels et collectifs du patient');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('8', 'Nouvel item. Les discriminations');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('9', 'Introduction à l’éthique médicale');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('10', 'Nouvel item. Approches transversales du corps');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('11', 'Violences et santé.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('12', 'Nouvel item. Violences sexuelles');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('13', 'Certificats médicaux. Décès et législation.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('14', 'Nouvel item. La mort');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('15', 'Soins psychiatriques sans consentement');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('16', 'Organisation du système de soins. Sa régulation. Les indicateurs. Parcours de soins.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('17', 'Nouvel item. Télémédecine, télésanté et téléservices en santé.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('18', 'Nouvel item. Santé et numérique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('19', 'La sécurité sociale. L''assurance maladie. Les assurances complémentaires. La complémentaire santé solidaire (CSS). La consommation médicale. Protection sociale. Consommation médicale et économie de la santé.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('20', 'La méthodologie de la recherche en santé');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('21', 'Mesure de l''état de santé de la population');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('22', 'Nouvel item. Maladies rares');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('23', 'Grossesse normale');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('24', 'Principales complications de la grossesse');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('25', 'Grossesse extra-utérine');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('26', 'Douleur abdominale aiguë chez une femme enceinte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('27', 'Prévention des risques fœtaux : infection, médicaments, toxiques, irradiation');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('28', 'Connaître les particularités de l''infection urinaire au cours de la grossesse');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('29', 'Connaître les principaux risques professionnels pour la maternité, liés au travail de la mère.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('30', 'Prématurité et retard de croissance intra-utérin : facteurs de risque et prévention');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('31', 'Accouchement, délivrance et suites de couches normales');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('32', 'Évaluation et soins du nouveau-né à terme');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('33', 'Allaitement maternel');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('34', 'Suites de couches pathologiques : pathologie maternelle dans les 40 jours');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('35', 'Anomalies du cycle menstruel. Métrorragies');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('36', 'Contraception');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('37', 'Interruption volontaire de grossesse');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('38', 'Infertilité du couple : conduite de la première consultation');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('39', 'Assistance médicale à la procréation : principaux aspects biologiques, médicaux et éthiques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('40', 'Algies pelviennes chez la femme');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('41', 'Nouvel item. Endométriose');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('42', 'Aménorrhée');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('43', 'Hémorragie génitale chez la femme');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('44', 'Tuméfaction pelvienne chez la femme');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('45', 'Spécificités des maladies génétiques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('46', 'Nouvel item. Médecine génomique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('47', 'Suivi d''un nourrisson, d''un enfant et d''un adolescent normal. Dépistage des anomalies orthopédiques, des troubles visuels, auditifs et dentaires. Examens de santé obligatoires. Médecine scolaire. Mortalité et morbidité infantiles.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('48', 'Alimentation et besoins nutritionnels du nourrisson et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('49', 'Puberté normale et pathologique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('50', 'Pathologie génito-scrotale chez le garçon et chez l''homme');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('51', 'Troubles de la miction chez l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('52', 'Strabisme et amblyopie de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('53', 'Retard de croissance staturo-pondérale');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('54', 'Boiterie chez l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('55', 'Développement psychomoteur du nourrisson et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('56', 'L''enfant handicapé : orientation et prise en charge (voir items 118, 121)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('57', 'Maltraitance et enfants en danger. Protection maternelle et infantile');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('58', 'Sexualité normale et ses troubles');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('59', 'Sujets en situation de précarité');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('60', 'Connaître les facteurs de risque, prévention, dépistage des troubles psychiques de l''enfant à la personne âgée');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('61', 'Connaître les bases des classifications des troubles mentaux de l''enfant à la personne âgée');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('62', 'Décrire l''organisation de l''offre de soins en psychiatrie, de l''enfant à la personne âgée');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('63', 'Trouble schizophrénique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('64', 'Trouble bipolaire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('65', 'Trouble délirant persistant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('66', 'Diagnostiquer : un trouble dépressif, un trouble anxieux généralisé, un trouble panique, un trouble phobique, un trouble obsessionnel compulsif, un état de stress post-traumatique, un trouble de l''adaptation (de l''enfant à la personne âgée), un trouble de la personnalité.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('67', 'Troubles envahissants du développement (voir items 118, 121, 122, 138)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('68', 'Troubles du comportement de l''adolescent');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('69', 'Troubles psychiques de la grossesse et du post-partum');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('70', 'Troubles psychiques du sujet âgé');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('71', 'Troubles des conduites alimentaires chez l''adolescent et l''adulte (voir item 251)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('72', 'Troubles à symptomatologie somatique et apparentés à tous les âges');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('73', 'Différents types de techniques psychothérapeutiques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('74', 'Prescription et surveillance des psychotropes (voir item 330)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('75', 'Addiction au tabac.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('76', 'Addiction à l''alcool.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('77', 'Addiction aux médicaments psychotropes (benzodiazépines et apparentés) (voir item 322)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('78', 'Addiction au cannabis, à la cocaïne, aux amphétamines, aux opiacés, aux drogues de synthèse (voir item 322)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('79', 'Addictions comportementales');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('80', 'Dopage et conduites dopantes (voir item 256)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('81', 'Altération chronique de la vision');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('82', 'Altération aiguë de la vision');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('83', 'Infections et inflammations oculaires');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('84', 'Glaucomes');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('85', 'Troubles de la réfraction');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('86', 'Pathologie des paupières');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('87', 'Epistaxis');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('88', 'Trouble aigu de la parole. Dysphonie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('89', 'Altération de la fonction auditive');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('90', 'Pathologie des glandes salivaires');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('91', 'Déficit neurologique récent (voir item 340)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('92', 'Déficit moteur et/ou sensitif des membres');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('93', 'Compression médullaire non traumatique et syndrome de la queue de cheval');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('94', 'Rachialgie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('95', 'Radiculalgie et syndrome canalaire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('96', 'Neuropathies périphériques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('97', 'Polyradiculonévrite aiguë inflammatoire (syndrome de Guillain-Barré)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('98', 'Myasthénie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('99', 'Migraine, névralgie du trijumeau et algies de la face');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('100', 'Céphalée inhabituelle aiguë et chronique chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('101', 'Paralysie faciale');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('102', 'Diplopie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('103', 'Vertige');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('104', 'Sclérose en plaques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('105', 'Épilepsie de l''enfant et de l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('106', 'Maladie de Parkinson');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('107', 'Mouvements anormaux');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('108', 'Confusion, démences (voir item 132)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('109', 'Troubles de la marche et de l''équilibre');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('110', 'Troubles du sommeil de l''enfant et de l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('111', 'Dermatoses faciales : acné, rosacée, dermatite séborrhéique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('112', 'Dermatose bulleuse touchant la peau et/ou les muqueuses externes');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('113', 'Hémangiomes et malformations vasculaires cutanées');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('114', 'Exanthème et érythrodermie de l''adulte et de l''enfant (voir item 164)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('115', 'Nouvel item. Toxidermies');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('116', 'Prurit');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('117', 'Psoriasis');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('118', 'La personne handicapée : bases de l''évaluation fonctionnelle et thérapeutique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('119', ' bis. Soin et accompagnement dans la maladie chronique et le handicap');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('120', 'Complications de l''immobilité et du décubitus. Prévention et prise en charge');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('121', 'Le handicap psychique (voir item 56 et 118)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('122', 'Principales techniques de rééducation et de réadaptation (voir item 55)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('123', 'Vieillissement normal : aspects biologiques, fonctionnels et relationnels. Données épidémiologiques et sociologiques. Prévention du vieillissement pathologique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('124', 'Ménopause, insuffisance ovarienne prématurée, andropause, déficit androgénique lié à l’âge');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('125', 'Troubles de la miction et incontinence urinaire de l''adulte et du sujet âgé');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('126', 'Trouble de l''érection');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('127', 'Hypertrophie bénigne de la prostate');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('128', 'Ostéopathies fragilisantes');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('129', 'Arthrose');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('130', 'La personne âgée malade : particularités sémiologiques, psychologiques et thérapeutiques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('131', 'Troubles de la marche et de l''équilibre (voir item 109)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('132', 'Troubles cognitifs du sujet âgé (voir item 108)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('133', 'Autonomie et dépendance chez le sujet âgé');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('134', 'Bases neurophysiologiques, mécanismes physiopathologiques d''une douleur aiguë et d''une douleur chronique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('135', 'Thérapeutiques antalgiques, médicamenteuses et non médicamenteuses');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('136', 'Anesthésie locale, locorégionale et générale');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('137', 'Douleur chez l''enfant : évaluation et traitements antalgiques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('138', 'Douleur chez la personne vulnérable');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('139', 'Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (1). Principaux repères cliniques. Modalités d''organisation des équipes, en établissement de santé et en et en ambulatoire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('140', 'Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (2). Accompagnement de la personne malade et de son entourage. Principaux repères éthiques.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('141', 'Soins palliatifs pluridisciplinaires chez un malade en phase palliative ou terminale d''une maladie grave, chronique ou létale (3). La sédation pour détresse en phase terminale et dans des situations spécifiques et complexes en fin de vie. Réponse à la demande d''euthanasie ou de suicide assisté.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('142', 'Connaître les aspects spécifiques des soins palliatifs en pédiatrie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('143', 'Connaître les aspects spécifiques des soins palliatifs en réanimation');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('144', 'Deuil normal et pathologique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('145', 'Surveillance des maladies infectieuses transmissibles');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('146', 'Vaccinations');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('147', 'Fièvre aiguë chez l''enfant et l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('148', 'Infections naso-sinusiennes de l''adulte et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('149', 'Angines de l''adulte et de l''enfant et rhinopharyngites de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('150', 'Otites infectieuses de l''adulte et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('151', 'Méningites, méningoencéphalites, abcès cérébral chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('152', 'Endocardite infectieuse');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('153', 'Surveillance des porteurs de valve et prothèses vasculaires');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('154', 'Infections broncho pulmonaires communautaires de l''adulte et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('155', 'Infections cutanéo-muqueuses et des phanères, bactériennes et mycosiques de l''adulte et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('156', 'Infections ostéo articulaires (IOA) de l''enfant et de l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('157', 'a. Septicémie/Bactériémie/Fongémie de l''adulte et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('158', 'b. Sepsis et choc septique de l’enfant et de l’adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('159', 'Tuberculose de l''adulte et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('160', 'Tétanos');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('161', 'Infections urinaires de l''enfant et de l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('162', 'Infections sexuellement transmissibles (IST) : gonococcies, chlamydioses, syphilis, papillomavirus humain (HPV), trichomonose');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('163', 'Coqueluche');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('164', 'Exanthèmes fébriles de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('165', 'Oreillons');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('166', 'Grippe');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('167', 'Hépatites virales');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('168', 'Infections à herpès virus du sujet immunocompétent');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('169', 'Infections à VIH');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('170', 'Paludisme');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('171', 'Gale et pédiculose');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('172', 'Parasitoses digestives : giardiose, amoebose, téniasis, ascaridiose, oxyurose, anguillulose, cryptosporidiose.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('173', 'Zoonoses');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('174', 'Pathologie infectieuse chez les migrants adultes et enfants');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('175', 'Voyage en pays tropical de l''adulte et de l''enfant : conseils avant le départ, pathologies du retour : fièvre, diarrhée, manifestations cutanées');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('176', 'Diarrhées infectieuses de l''adulte et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('177', 'Prescription et surveillance des anti-infectieux chez l''adulte et l''enfant (voir item 330)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('178', 'Risques émergents, bioterrorisme, maladies hautement transmissibles');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('179', 'Risques sanitaires liés à l''eau et à l''alimentation. Toxi-infections alimentaires');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('180', 'Risques sanitaires liés aux irradiations. Radioprotection');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('181', 'La sécurité sanitaire des produits destinés à l''homme. La veille sanitaire (voir item 325)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('182', 'Environnement professionnel et santé au travail');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('183', 'Organisation de la médecine du travail. Prévention des risques professionnels');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('184', 'Accidents du travail et maladies professionnelles : définitions et enjeux');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('185', 'Réaction inflammatoire : aspects biologiques et cliniques. Conduite à tenir');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('186', 'Hypersensibilités et allergies chez l''enfant et l''adulte : aspects physiopathologiques, épidémiologiques, diagnostiques et principes de traitement');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('187', 'Hypersensibilités et allergies cutanéomuqueuses chez l''enfant et l''adulte. Urticaire, dermatites atopique et de contact, conjonctivite allergique.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('188', 'Hypersensibilité et allergies respiratoires chez l''enfant et chez l''adulte. Asthme, rhinite');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('189', 'Déficit immunitaire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('190', 'Fièvre prolongée');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('191', 'Fièvre chez un patient immunodéprimé');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('192', 'Pathologies auto-immunes : aspects épidémiologiques, diagnostiques et principes de traitement');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('193', 'Connaître les principaux types de vascularite systémique, les organes cibles, les outils diagnostiques et les moyens thérapeutiques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('194', 'Lupus systémique. Syndrome des anti-phospholipides (SAPL)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('195', 'Artérite à cellules géantes');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('196', 'Polyarthrite rhumatoïde');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('197', 'Spondyloarthrite');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('198', 'Arthropathie microcristalline');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('199', 'Syndrome douloureux régional complexe (ex algodystrophie)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('200', 'Douleur et épanchement articulaire. Arthrite d''évolution récente');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('201', 'Transplantation d''organes : aspects épidémiologiques et immunologiques ; principes de traitement; complications et pronostic ; aspects éthiques et légaux. Prélèvements d''organes et législation.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('202', 'Biothérapies et thérapies ciblées');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('203', 'Dyspnée aiguë et chronique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('204', 'Toux chez l''enfant et chez l''adulte (avec le traitement)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('205', 'Hémoptysie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('206', 'Épanchement pleural liquidien');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('207', 'Opacités et masses intra-thoraciques chez l''enfant et chez l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('208', 'Insuffisance respiratoire chronique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('209', 'Bronchopneumopathie chronique obstructive chez l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('210', 'Pneumopathie interstitielle diffuse');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('211', 'Sarcoïdose');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('212', 'Hémogramme chez l''adulte et l''enfant : indications et interprétation');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('213', 'Anémie chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('214', 'Thrombopénie chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('215', 'Purpuras chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('216', 'Syndrome hémorragique d''origine hématologique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('217', 'Syndrome mononucléosique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('218', 'Éosinophilie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('219', 'Pathologie du fer chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('220', 'No 216. Adénopathie superficielle de l''adulte et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('221', 'Athérome : épidémiologie et physiopathologie. Le malade poly- athéromateux');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('222', 'Facteurs de risque cardio-vasculaire et prévention');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('223', 'Dyslipidémies');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('224', 'Hypertension artérielle de l''adulte et de l’enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('225', 'Artériopathie oblitérante de l''aorte, des artères viscérales et des membres inférieurs ; anévrysmes');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('226', 'Thrombose veineuse profonde et embolie pulmonaire (voir item 330)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('227', 'Insuffisance veineuse chronique. Varices');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('228', 'Ulcère de jambe');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('229', 'Surveillance et complications des abords veineux');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('230', 'Douleur thoracique aiguë');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('231', 'Électrocardiogramme : indications et interprétations');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('232', 'Fibrillation atriale');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('233', 'Valvulopathies');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('234', 'Insuffisance cardiaque de l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('235', 'Péricardite aiguë');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('236', 'Troubles de la conduction intracardiaque');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('237', 'Palpitations');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('238', 'Souffle cardiaque chez l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('239', 'Acrosyndromes (phénomène de Raynaud, érythermalgie, acrocyanose, engelures, ischémie digitale)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('240', 'Hypoglycémie chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('241', 'Goitre, nodules thyroïdiens et cancers thyroïdiens');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('242', 'Hyperthyroïdie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('243', 'Hypothyroïdie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('244', 'Adénome hypophysaire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('245', 'Insuffisance surrénale chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('246', 'Gynécomastie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('247', 'Diabète sucré de types 1 et 2 de l''enfant et de l''adulte. Complications');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('248', 'Prévention primaire par la nutrition chez l''adulte et chez l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('249', 'Modifications thérapeutiques du mode de vie (alimentation et activité physique) chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('250', 'Dénutrition chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('251', 'Amaigrissement à tous les âges');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('252', 'Troubles nutritionnels chez le sujet âgé');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('253', 'Obésité de l''enfant et de l''adulte (voir item 71)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('254', 'a. Besoins nutritionnels et grossesse');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('255', 'b. Diabète gestationnel');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('256', 'Aptitude au sport chez l''adulte et l''enfant ; besoins nutritionnels chez le sportif (voir item 80)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('257', 'Œdèmes des membres inférieurs localisés ou généralisés');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('258', 'Élévation de la créatininémie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('259', 'Protéinurie et syndrome néphrotique de chez l''l''adulte et de l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('260', 'Hématurie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('261', 'Néphropathie glomérulaire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('262', 'Néphropathies interstitielles');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('263', 'Néphropathies vasculaires');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('264', 'Insuffisance rénale chronique chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('265', 'Lithiase urinaire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('266', 'Polykystose rénale');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('267', 'Troubles de l''équilibre acido-basique et désordres hydro-électrolytiques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('268', 'Hypercalcémie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('269', 'a. Douleurs abdominales aiguës chez l''enfant et chez l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('270', 'b. Douleurs lombaires aiguës chez l''enfant et chez l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('271', 'Reflux gastro-œsophagien chez le nourrisson, chez l''enfant et chez l''adulte. Hernie hiatale');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('272', 'Ulcère gastrique et duodénal. Gastrite');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('273', 'Dysphagie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('274', 'Vomissements du nourrisson, de l''enfant et de l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('275', 'Splénomégalie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('276', 'Hépatomégalie et masse abdominale');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('277', 'Lithiase biliaire et complications');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('278', 'Ictère');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('279', 'Cirrhose et complications');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('280', 'Ascite');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('281', 'Pancréatite chronique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('282', 'Maladies Inflammatoires Chroniques de l''Intestin (MICI) chez l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('283', 'Constipation chez l''enfant et l''adulte (avec le traitement)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('284', 'Colopathie fonctionnelle');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('285', 'Diarrhée chronique chez l''adulte et l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('286', 'Diarrhée aiguë et déshydratation chez le nourrisson, l''enfant et l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('287', 'Diverticulose colique et diverticulite aiguë du sigmoïde');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('288', 'Pathologie hémorroïdaire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('289', 'Hernie pariétale chez l''enfant et l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('290', 'Épidémiologie, facteurs de risque, prévention et dépistage des cancers');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('291', 'Cancer : cancérogénèse, oncogénétique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('292', 'Diagnostic des cancers : signes d''appel et investigations para-cliniques ; caractérisation du stade ; pronostic');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('293', 'Le médecin préleveur de cellules et/ou de tissus pour des examens d''Anatomie et Cytologie Pathologiques : connaître les principes de réalisation, transmission et utilisation des prélèvements à visée sanitaire et de recherche');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('294', 'Traitement des cancers : principales modalités, classes thérapeutiques et leurs complications majeures. La décision thérapeutique pluridisciplinaire et l''information du malade');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('295', 'Prise en charge et accompagnement d''un malade atteint de cancer à tous les stades de la maladie dont le stade de soins palliatifs en abordant les problématiques techniques, relationnelles, sociales et éthiques. Traitements symptomatiques. Modalités de surveillance.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('296', 'Agranulocytose médicamenteuse : conduite à tenir');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('297', 'Cancer de l''enfant : particularités épidémiologiques, diagnostiques et thérapeutiques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('298', 'Tumeurs de la cavité buccale, naso-sinusiennes et du cavum, et des voies aérodigestives supérieures.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('299', 'Tumeurs intracrâniennes');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('300', 'Tumeurs du col utérin, tumeur du corps utérin');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('301', 'Tumeurs du colon et du rectum');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('302', 'Tumeurs cutanées, épithéliales et mélaniques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('303', 'Tumeurs de l''estomac');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('304', 'Tumeurs du foie, primitives et secondaires');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('305', 'Tumeurs de l''œsophage');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('306', 'Tumeurs de l''ovaire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('307', 'Tumeurs des os primitives et secondaires');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('308', 'Tumeurs du pancréas');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('309', 'Tumeurs du poumon, primitives et secondaires');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('310', 'Tumeurs de la prostate');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('311', 'Tumeurs du rein de l’adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('312', 'Tumeurs du sein');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('313', 'Tumeurs du testicule');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('314', 'Tumeurs vésicales');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('315', 'Leucémies aiguës');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('316', 'Syndromes myélodysplasiques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('317', 'Syndromes myéloprolifératifs');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('318', 'Leucémies lymphoïdes chroniques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('319', 'Lymphomes malins');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('320', 'Myélome multiple des os');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('321', 'Principe du bon usage du médicament');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('322', 'La décision thérapeutique personnalisée : bon usage dans des situations à risque');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('323', 'Analyser et utiliser les résultats des études cliniques dans la perspective du bon usage - analyse critique, recherche clinique et niveaux de preuve (voir item 3)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('324', 'Éducation thérapeutique, observance et automédication');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('325', 'Identification et gestion des risques liés aux médicaments et aux biomatériaux, risque iatrogène, erreur médicamenteuse (voir item 4 et item 5)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('326', 'Cadre réglementaire de la prescription thérapeutique et recommandations pour le bon usage');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('327', 'Nouvel item. Principes de la médecine intégrative, utilité et risques des interventions non médicamenteuses et des thérapies complémentaires');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('328', 'Thérapeutiques non médicamenteuses et dispositifs médicaux');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('329', 'Transfusion sanguine et produits dérivés du sang : indications, complications. Hémovigilance');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('330', 'Prescription et surveillance des classes de médicaments les plus courantes chez l''adulte et chez l''enfant, hors anti-infectieux (voir item 174). Connaitre les grands principes thérapeutiques.');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('331', 'Arrêt cardio-circulatoire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('332', 'État de choc. Principales étiologies : hypovolémique, septique (voir item 158), cardiogénique, anaphylactique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('333', 'Nouvel item. Situations sanitaires exceptionnelles');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('334', 'Prise en charge immédiate pré-hospitalière et à l''arrivée à l''hôpital, évaluation des complications chez : un brûlé, un traumatisé sévère, un traumatisé thoracique, un traumatisé abdominal, un traumatisé des membres et/ou du bassin, un traumatisé du rachis ou vertébro-médullaire, un traumatisé crânien ou crânio- encéphalique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('335', 'Orientation diagnostique et conduite à tenir devant un traumatisme maxillo- facial et oculaire');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('336', 'Coma non traumatique chez l''adulte et chez l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('337', 'Principales intoxications aiguës');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('338', 'Œdème de Quincke et anaphylaxie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('339', 'Syndromes coronariens aigus');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('340', 'Accidents vasculaires cérébraux');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('341', 'Hémorragie méningée');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('342', 'Malaise, perte de connaissance, crise convulsive chez l''adulte (voir item 105)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('343', 'État confusionnel et trouble de conscience chez l''adulte et chez l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('344', 'Prise en charge d''une patiente atteinte de pré-éclampsie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('345', 'Malaise grave du nourrisson et mort inattendue du nourrisson');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('346', 'Convulsions chez le nourrisson et chez l''enfant');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('347', 'Rétention aiguë d''urine');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('348', 'Insuffisance rénale aiguë - Anurie');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('349', 'Infection aiguë des parties molles (abcès, panaris, phlegmon des gaines)');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('350', 'Grosse jambe rouge aiguë');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('351', 'Agitation et délire aiguë');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('352', 'Crise d''angoisse aiguë et attaque de panique');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('353', 'Risque et conduite suicidaires chez l''enfant, l''adolescent et l''adulte : identification et prise en charge');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('354', 'Syndrome occlusif de l''enfant et de l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('355', 'Hémorragie digestive');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('356', 'Appendicite de l''enfant et de l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('357', 'No 352. Péritonite aiguë chez l''enfant et chez l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('358', 'Pancréatite aiguë');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('359', 'Détresse et insuffisance respiratoire aigüe du nourrisson, de l''enfant et de l''adulte');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('360', 'Pneumothorax');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('361', 'Lésions péri-articulaires et ligamentaires du genou, de la cheville et de l''épaule');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('362', 'Prothèses et ostéosynthèses');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('363', 'Fractures fréquentes de l''adulte et du sujet âgé');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('364', 'Fractures chez l''enfant : particularités épidémiologiques, diagnostiques et thérapeutiques');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('365', 'Surveillance d''un malade sous plâtre/résine, diagnostiquer une complication');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('366', 'Exposition accidentelle aux liquides biologiques : conduite à tenir');
INSERT INTO nouveau_programme_r2c (unnamed_0, unnamed_1) VALUES ('367', 'Nouvel item. Impact de l’environnement sur la santé.');